# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kECS9XDsGlAPvyZ6eQ9ccYQ_IMmilCwm
"""

import streamlit as st
import pandas as pd
import joblib

# Load the model
model = joblib.load("best_sgd_pipeline_updated.pkl")

st.title("Security-Aware Resource Allocation Prediction")

# Option 1: Manual input
st.header("Manual Input")
cpu = st.number_input("CPU Utilization (%)", min_value=0, max_value=100, value=50)
mem = st.number_input("Memory Utilization (%)", min_value=0, max_value=100, value=50)
net_in = st.number_input("Network In", value=100)
net_out = st.number_input("Network Out", value=100)
disk = st.number_input("Disk IO (%)", min_value=0, max_value=100, value=30)

input_df = pd.DataFrame([{
    'cpu_util_percent': cpu,
    'mem_util_percent': mem,
    'net_in': net_in,
    'net_out': net_out,
    'disk_io_percent': disk
}])

# Predict
if st.button("Predict Allocation"):
    # Your existing predict_and_allocate function can be called here
    input_df['Failure_Probability'] = model.predict_proba(input_df)[:,1]
    input_df['Failure_Predicted'] = input_df['Failure_Probability'] > 0.5
    st.write("Prediction Result:")
    st.dataframe(input_df)